version: 2.1
jobs:
  build:
    working_directory: /go/src/github.com/ghdwlsgur/gostat
    docker:
      - image: golang:1.20.4
    environment:
      GOPATH: /go
    steps:
      - checkout
      - run:
          name: RUN UNIT TEST
          environment:
            GO111MODULE: "on"
          command: bash scripts/deploy.sh test_with_circleci
workflows:
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
          context: develop
